version: "3"

services:
  web:
    container_name: docker.pkg.github.com/adriantintpilver/visual-cancerdb/visual-cancerdb-nodejs
    restart: always
    build: .
    ports:
      - "3000:3000"    
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: docker.pkg.github.com/adriantintpilver/visual-cancerdb/visual-cancerdb-mongo
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
       - ./data:/data/db
    logging:
      driver: none



      
