name: BuildRun
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        

    steps:

    - uses: actions/checkout@v1
    - run: docker-compose build
    - run: docker ps
    - name: docker compose UP -d
      run: docker-compose up -d
    - name: Sleep for 120 seconds
      run: sleep 120s
    - name: docker ps
      run: docker ps
    - name: Sleep for 120 seconds
      run: sleep 120s
    - name: docker ps
      run: docker ps
    - name: Sleep for 120 seconds
      run: sleep 120s
    - name: docker ps
      run: docker ps
