name: BuildRun

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
                      
    - uses: actions/checkout@v1
    - run: docker-compose build
    - run: docker-compose up -d
    - run: docker ps
                                  
