name: BuildRun

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - uses: actions/checkout@v1
    - run: docker-compose build
    - run: docker-compose up
    - run: docker ps -a
    - uses: jakejarvis/wait-action@master
      with:
        time: '300s'
    - run: docker ps -a
    - uses: jakejarvis/wait-action@master
      with:
        time: '300s'
    - run: docker ps -a 