on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker-compose
      run: docker-compose build
    - name: UP docker-compose
      run: docker-compose up
