on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: Build docker-compose
      uses: docker-compose build
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adriantintpilver/Visual-CancerDB@main
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}